#@data/values
---
projectName: bpt-next-web
productionDomain: bpt-next-web.binpar.cloud
additionalDeployEnvSources:
  - configMapRef:
      name: web-config
      optional: false
configMaps:
  - name: web-config
    environment: test
    data:
      ambient: test
  - name: web-config
    environment: release
    data:
      ambient: release
